# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 629e0eebd45984f215d195de615f9f5a712f5443be4f17f45c207b973dccd9210a893a5cc380080f77247f38c6308a977bc43d99ba1da6fd71c2758be14245ec

test:
  secret_key_base: b2f6df7434f0414069ac9b960b4aceddc61994501c2ce5b9e67a1255e535bddd4b118d9d51638561ac06b2be8fedf55de0ea54682f9dc70d7758f306b212998b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
